package org.apache.ranger.authorization.spark.authorizer

/**
 * Subset of HiveOperationTypes supported by Apache Spark.
 *
 */
object SparkOperationType extends Enumeration {
  type SparkOperationType = Value

  val
  ALTERDATABASE, ALTERTABLE_ADDCOLS, ALTERTABLE_ADDPARTS, ALTERTABLE_RENAMECOL,
  ALTERTABLE_DROPPARTS, MSCK, ALTERTABLE_RENAMEPART, ALTERTABLE_RENAME,
  ALTERVIEW_RENAME, ALTERTABLE_PROPERTIES, ALTERTABLE_SERDEPROPERTIES,
  ALTERTABLE_LOCATION, QUERY, CREATEDATABASE, CREATETABLE_AS_SELECT, CREATEFUNCTION, CREATETABLE,
  CREATEVIEW, DESCTABLE, DESCDATABASE, DESCFUNCTION, DROPDATABASE, DROPTABLE, DROPFUNCTION, LOAD,
  SHOWCONF, SWITCHDATABASE, SHOW_CREATETABLE, SHOWCOLUMNS, SHOWDATABASES, SHOWFUNCTIONS,
  SHOWPARTITIONS, SHOWTABLES, SHOW_TBLPROPERTIES, TRUNCATETABLE, DROPVIEW, EXPLAIN,
  CACHE, STREAM, MUTATION, DATA_MAP, MANAGEMENT, ALTERDATABASE_LOCATION, DESCQUERY, REFRESHFUNCTION,
  REFRESHTABLE, SHOWVIEWS = Value

}
